/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/brain.gltf --transform 
Files: public/models/brain.gltf [12.92KB] > C:\Users\minse\Desktop\Game\neuro-atlas\brain-transformed.glb [367.03KB] (-2741%)
Author: Dean Lavery (https://sketchfab.com/dean.lavery)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/brain-project-24ec03412dd8432bb0d3e750a72608e0
Title: Brain Project
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/brain-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Brain_Part_01_Colour_Brain_Texture_0.geometry} material={materials.Colour_Brain_Texture} />
    </group>
  )
}

useGLTF.preload('/brain-transformed.glb')
